some fix

diff --git a/Dip/configure b/Dip/configure
--- a/Dip/configure
+++ b/Dip/configure
@@ -483,7 +483,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os ALWAYS_FALSE_TRUE ALWAYS_FALSE_FALSE have_svnversion DIP_SVN_REV CDEFS ADD_CFLAGS DBG_CFLAGS OPT_CFLAGS sol_cc_compiler CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT COIN_CC_IS_CL_TRUE COIN_CC_IS_CL_FALSE MPICC CXXDEFS ADD_CXXFLAGS DBG_CXXFLAGS OPT_CXXFLAGS CXX CXXFLAGS ac_ct_CXX COIN_CXX_IS_CL_TRUE COIN_CXX_IS_CL_FALSE MPICXX EGREP LN_S INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT LIBTOOLM4 have_autoconf have_automake have_svn BUILDTOOLSDIR AUX_DIR abs_source_dir abs_lib_dir abs_include_dir abs_bin_dir HAVE_EXTERNALS_TRUE HAVE_EXTERNALS_FALSE host host_cpu host_vendor host_os ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL ac_c_preproc_warn_flag ac_cxx_preproc_warn_flag RPATH_FLAGS LT_LDFLAGS PKG_CONFIG ac_ct_PKG_CONFIG COIN_HAS_PKGCONFIG_TRUE COIN_HAS_PKGCONFIG_FALSE COIN_PKG_CONFIG_PATH COIN_PKG_CONFIG_PATH_UNINSTALLED COINDEPEND_LIBS COINDEPEND_CFLAGS COINDEPEND_DATA COINDEPEND_DEPENDENCIES COINDEPEND_LIBS_INSTALLED COINDEPEND_CFLAGS_INSTALLED COINDEPEND_DATA_INSTALLED DIPLIB_CFLAGS DIPLIB_LIBS DIPLIB_PCLIBS DIPLIB_PCREQUIRES DIPLIB_DEPENDENCIES DIPLIB_CFLAGS_INSTALLED DIPLIB_LIBS_INSTALLED COIN_HAS_COINDEPEND_TRUE COIN_HAS_COINDEPEND_FALSE CLP_LIBS CLP_CFLAGS CLP_DATA CLP_DEPENDENCIES CLP_LIBS_INSTALLED CLP_CFLAGS_INSTALLED CLP_DATA_INSTALLED COIN_HAS_CLP_TRUE COIN_HAS_CLP_FALSE SAMPLE_LIBS SAMPLE_CFLAGS SAMPLE_DATA SAMPLE_DEPENDENCIES SAMPLE_LIBS_INSTALLED SAMPLE_CFLAGS_INSTALLED SAMPLE_DATA_INSTALLED COIN_HAS_SAMPLE_TRUE COIN_HAS_SAMPLE_FALSE CGL_LIBS CGL_CFLAGS CGL_DATA CGL_DEPENDENCIES CGL_LIBS_INSTALLED CGL_CFLAGS_INSTALLED CGL_DATA_INSTALLED COIN_HAS_CGL_TRUE COIN_HAS_CGL_FALSE CBC_LIBS CBC_CFLAGS CBC_DATA CBC_DEPENDENCIES CBC_LIBS_INSTALLED CBC_CFLAGS_INSTALLED CBC_DATA_INSTALLED COIN_HAS_CBC_TRUE COIN_HAS_CBC_FALSE CPX_LIBS CPX_CFLAGS CPX_DATA CPX_DEPENDENCIES CPX_LIBS_INSTALLED CPX_CFLAGS_INSTALLED CPX_DATA_INSTALLED COIN_HAS_CPX_TRUE COIN_HAS_CPX_FALSE SYMPHONY_LIBS SYMPHONY_CFLAGS SYMPHONY_DATA SYMPHONY_DEPENDENCIES SYMPHONY_LIBS_INSTALLED SYMPHONY_CFLAGS_INSTALLED SYMPHONY_DATA_INSTALLED COIN_HAS_SYMPHONY_TRUE COIN_HAS_SYMPHONY_FALSE ASL_LIBS ASL_CFLAGS ASL_DATA ASL_DEPENDENCIES ASL_LIBS_INSTALLED ASL_CFLAGS_INSTALLED ASL_DATA_INSTALLED COIN_HAS_ASL_TRUE COIN_HAS_ASL_FALSE HMETISINCDIR HMETISLIB COIN_HAS_HMETIS_TRUE COIN_HAS_HMETIS_FALSE OPENMP_TRUE OPENMP_FALSE PYTHON PYTHON_VERSION PYTHON_PREFIX PYTHON_EXEC_PREFIX PYTHON_PLATFORM pythondir pkgpythondir pyexecdir pkgpyexecdir HAVE_PYTHON_TRUE HAVE_PYTHON_FALSE PYTHON_LIBS PYTHON_CFLAGS CLP_LP_SOLVER_TRUE CLP_LP_SOLVER_FALSE CPLEX_LP_SOLVER_TRUE CPLEX_LP_SOLVER_FALSE SYMPHONY_IP_SOLVER_TRUE SYMPHONY_IP_SOLVER_FALSE CBC_IP_SOLVER_TRUE CBC_IP_SOLVER_FALSE CPLEX_IP_SOLVER_TRUE CPLEX_IP_SOLVER_FALSE DIPINCDIR DIPSRCDIR DipDEFS ARCH COIN_HAS_CLP LIBEXT VPATH_DISTCLEANFILES ABSBUILDDIR LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os ALWAYS_FALSE_TRUE ALWAYS_FALSE_FALSE have_svnversion DIP_SVN_REV CDEFS ADD_CFLAGS DBG_CFLAGS OPT_CFLAGS sol_cc_compiler CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT COIN_CC_IS_CL_TRUE COIN_CC_IS_CL_FALSE MPICC CXXDEFS ADD_CXXFLAGS DBG_CXXFLAGS OPT_CXXFLAGS CXX CXXFLAGS ac_ct_CXX COIN_CXX_IS_CL_TRUE COIN_CXX_IS_CL_FALSE MPICXX EGREP LN_S INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT LIBTOOLM4 have_autoconf have_automake have_svn BUILDTOOLSDIR AUX_DIR abs_source_dir abs_lib_dir abs_include_dir abs_bin_dir HAVE_EXTERNALS_TRUE HAVE_EXTERNALS_FALSE host host_cpu host_vendor host_os ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL ac_c_preproc_warn_flag ac_cxx_preproc_warn_flag RPATH_FLAGS LT_LDFLAGS PKG_CONFIG ac_ct_PKG_CONFIG COIN_HAS_PKGCONFIG_TRUE COIN_HAS_PKGCONFIG_FALSE COIN_PKG_CONFIG_PATH COIN_PKG_CONFIG_PATH_UNINSTALLED COINDEPEND_LIBS COINDEPEND_CFLAGS COINDEPEND_DATA COINDEPEND_DEPENDENCIES COINDEPEND_LIBS_INSTALLED COINDEPEND_CFLAGS_INSTALLED COINDEPEND_DATA_INSTALLED DIPLIB_CFLAGS DIPLIB_LIBS DIPLIB_PCLIBS DIPLIB_PCREQUIRES DIPLIB_DEPENDENCIES DIPLIB_CFLAGS_INSTALLED DIPLIB_LIBS_INSTALLED COIN_HAS_COINDEPEND_TRUE COIN_HAS_COINDEPEND_FALSE CLP_LIBS CLP_CFLAGS CLP_DATA CLP_DEPENDENCIES CLP_LIBS_INSTALLED CLP_CFLAGS_INSTALLED CLP_DATA_INSTALLED COIN_HAS_CLP_TRUE COIN_HAS_CLP_FALSE SAMPLE_LIBS SAMPLE_CFLAGS SAMPLE_DATA SAMPLE_DEPENDENCIES SAMPLE_LIBS_INSTALLED SAMPLE_CFLAGS_INSTALLED SAMPLE_DATA_INSTALLED COIN_HAS_SAMPLE_TRUE COIN_HAS_SAMPLE_FALSE CGL_LIBS CGL_CFLAGS CGL_DATA CGL_DEPENDENCIES CGL_LIBS_INSTALLED CGL_CFLAGS_INSTALLED CGL_DATA_INSTALLED COIN_HAS_CGL_TRUE COIN_HAS_CGL_FALSE CBC_LIBS CBC_CFLAGS CBC_DATA CBC_DEPENDENCIES CBC_LIBS_INSTALLED CBC_CFLAGS_INSTALLED CBC_DATA_INSTALLED COIN_HAS_CBC_TRUE COIN_HAS_CBC_FALSE CPX_LIBS CPX_CFLAGS CPX_DATA CPX_DEPENDENCIES CPX_LIBS_INSTALLED CPX_CFLAGS_INSTALLED CPX_DATA_INSTALLED COIN_HAS_CPX_TRUE COIN_HAS_CPX_FALSE SYMPHONY_LIBS SYMPHONY_CFLAGS SYMPHONY_DATA SYMPHONY_DEPENDENCIES SYMPHONY_LIBS_INSTALLED SYMPHONY_CFLAGS_INSTALLED SYMPHONY_DATA_INSTALLED COIN_HAS_SYMPHONY_TRUE COIN_HAS_SYMPHONY_FALSE ASL_LIBS ASL_CFLAGS ASL_DATA ASL_DEPENDENCIES ASL_LIBS_INSTALLED ASL_CFLAGS_INSTALLED ASL_DATA_INSTALLED COIN_HAS_ASL_TRUE COIN_HAS_ASL_FALSE HMETISINCDIR HMETISLIB COIN_HAS_HMETIS_TRUE COIN_HAS_HMETIS_FALSE OPENMP_TRUE OPENMP_FALSE PYTHON PYTHON_VERSION PYTHON_PREFIX PYTHON_EXEC_PREFIX PYTHON_PLATFORM pythondir pkgpythondir pyexecdir pkgpyexecdir HAVE_PYTHON_TRUE HAVE_PYTHON_FALSE PYTHON_LIBS PYTHON_CFLAGS CLP_LP_SOLVER_TRUE CLP_LP_SOLVER_FALSE CPLEX_LP_SOLVER_TRUE CPLEX_LP_SOLVER_FALSE CBC_IP_SOLVER_TRUE CBC_IP_SOLVER_FALSE CPLEX_IP_SOLVER_TRUE CPLEX_IP_SOLVER_FALSE SYMPHONY_IP_SOLVER_TRUE SYMPHONY_IP_SOLVER_FALSE DIPINCDIR DIPSRCDIR DipDEFS ARCH COIN_HAS_CLP LIBEXT VPATH_DISTCLEANFILES ABSBUILDDIR LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -25564,9 +25564,9 @@ fi
 echo "$as_me:$LINENO: checking for Dip default lp solver" >&5
 echo $ECHO_N "checking for Dip default lp solver... $ECHO_C" >&6
 
-# Check whether --with-lp-solver or --without-lp-solver was given.
-if test "${with_lp_solver+set}" = set; then
-  withval="$with_lp_solver"
+# Check whether --with-dip-lp-solver or --without-dip-lp-solver was given.
+if test "${with_dip_lp_solver+set}" = set; then
+  withval="$with_dip_lp_solver"
   dip_lp_solver=$withval
 else
   dip_lp_solver=clp
@@ -25586,13 +25586,6 @@ echo "${ECHO_T}Clp" >&6
 echo "${ECHO_T}Cplex" >&6
      if test $coin_has_cpx != yes; then
          found_package=false
-     fi
-   ;;
-   symphony)
-     echo "$as_me:$LINENO: result: " >&5
-echo "${ECHO_T}" >&6{symphony}
-     if test $coin_has_symphony != yes; then
-     	found_package=false
      fi
    ;;
   *)
@@ -25633,18 +25626,6 @@ else
 fi
 
 
-
-if test $dip_ip_solver = symphony &&
-test $coin_has_symphony != unavailable &&
-test $coin_has_symphony != skipping; then
-  SYMPHONY_IP_SOLVER_TRUE=
-  SYMPHONY_IP_SOLVER_FALSE='#'
-else
-  SYMPHONY_IP_SOLVER_TRUE='#'
-  SYMPHONY_IP_SOLVER_FALSE=
-fi
-
-
 #############################################################################
 #                      Check for the IP solver                              #
 #############################################################################
@@ -25652,9 +25633,9 @@ fi
 echo "$as_me:$LINENO: checking for DIP default ip solver" >&5
 echo $ECHO_N "checking for DIP default ip solver... $ECHO_C" >&6
 
-# Check whether --with-ip-solver or --without-ip-solver was given.
-if test "${with_ip_solver+set}" = set; then
-  withval="$with_ip_solver"
+# Check whether --with-dip-ip-solver or --without-dip-ip-solver was given.
+if test "${with_dip_ip_solver+set}" = set; then
+  withval="$with_dip_ip_solver"
   dip_ip_solver=$withval
 else
   dip_ip_solver=cbc
@@ -25674,6 +25655,13 @@ echo "${ECHO_T}Cbc" >&6
 echo "${ECHO_T}Cplex" >&6
      if test $coin_has_cpx != yes; then
          found_package=false
+     fi
+   ;;
+   symphony)
+     echo "$as_me:$LINENO: result: " >&5
+echo "${ECHO_T}" >&6{symphony}
+     if test $coin_has_symphony != yes; then
+     	found_package=false
      fi
    ;;
   *)
@@ -25711,6 +25699,18 @@ test $coin_has_cpx != skipping; then
 else
   CPLEX_IP_SOLVER_TRUE='#'
   CPLEX_IP_SOLVER_FALSE=
+fi
+
+
+
+if test $dip_ip_solver = symphony &&
+test $coin_has_symphony != unavailable &&
+test $coin_has_symphony != skipping; then
+  SYMPHONY_IP_SOLVER_TRUE=
+  SYMPHONY_IP_SOLVER_FALSE='#'
+else
+  SYMPHONY_IP_SOLVER_TRUE='#'
+  SYMPHONY_IP_SOLVER_FALSE=
 fi
 
 
@@ -26136,13 +26136,6 @@ echo "$as_me: error: conditional \"CPLEX_LP_SOLVER\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
-if test -z "${SYMPHONY_IP_SOLVER_TRUE}" && test -z "${SYMPHONY_IP_SOLVER_FALSE}"; then
-  { { echo "$as_me:$LINENO: error: conditional \"SYMPHONY_IP_SOLVER\" was never defined.
-Usually this means the macro was only invoked conditionally." >&5
-echo "$as_me: error: conditional \"SYMPHONY_IP_SOLVER\" was never defined.
-Usually this means the macro was only invoked conditionally." >&2;}
-   { (exit 1); exit 1; }; }
-fi
 if test -z "${CBC_IP_SOLVER_TRUE}" && test -z "${CBC_IP_SOLVER_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"CBC_IP_SOLVER\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -26154,6 +26147,13 @@ if test -z "${CPLEX_IP_SOLVER_TRUE}" && test -z "${CPLEX_IP_SOLVER_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"CPLEX_IP_SOLVER\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"CPLEX_IP_SOLVER\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${SYMPHONY_IP_SOLVER_TRUE}" && test -z "${SYMPHONY_IP_SOLVER_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"SYMPHONY_IP_SOLVER\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"SYMPHONY_IP_SOLVER\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -26971,12 +26971,12 @@ s,@CLP_LP_SOLVER_TRUE@,$CLP_LP_SOLVER_TRUE,;t t
 s,@CLP_LP_SOLVER_FALSE@,$CLP_LP_SOLVER_FALSE,;t t
 s,@CPLEX_LP_SOLVER_TRUE@,$CPLEX_LP_SOLVER_TRUE,;t t
 s,@CPLEX_LP_SOLVER_FALSE@,$CPLEX_LP_SOLVER_FALSE,;t t
-s,@SYMPHONY_IP_SOLVER_TRUE@,$SYMPHONY_IP_SOLVER_TRUE,;t t
-s,@SYMPHONY_IP_SOLVER_FALSE@,$SYMPHONY_IP_SOLVER_FALSE,;t t
 s,@CBC_IP_SOLVER_TRUE@,$CBC_IP_SOLVER_TRUE,;t t
 s,@CBC_IP_SOLVER_FALSE@,$CBC_IP_SOLVER_FALSE,;t t
 s,@CPLEX_IP_SOLVER_TRUE@,$CPLEX_IP_SOLVER_TRUE,;t t
 s,@CPLEX_IP_SOLVER_FALSE@,$CPLEX_IP_SOLVER_FALSE,;t t
+s,@SYMPHONY_IP_SOLVER_TRUE@,$SYMPHONY_IP_SOLVER_TRUE,;t t
+s,@SYMPHONY_IP_SOLVER_FALSE@,$SYMPHONY_IP_SOLVER_FALSE,;t t
 s,@DIPINCDIR@,$DIPINCDIR,;t t
 s,@DIPSRCDIR@,$DIPSRCDIR,;t t
 s,@DipDEFS@,$DipDEFS,;t t
